"""KBO Sabermetrics metric catalog.

Each entry follows MetricDefinition schema:
  name, display_name, category, formula, interpretation,
  implementation_status, context_neutral, context_dependent,
  higher_is_better, version, notes
"""

METRIC_CATALOG: list[dict] = [
    # ──────────────────────────────────────────
    # 타격 기본 counting stats (observed)
    # ──────────────────────────────────────────
    {
        "name": "PA",
        "display_name": "타석",
        "category": "observed",
        "formula": "AB + BB + HBP + SF + SH",
        "interpretation": "타석에 선 횟수. AB보다 완전한 공격 기회 측정치.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "AB",
        "display_name": "타수",
        "category": "observed",
        "formula": "PA - BB - HBP - SF - SH",
        "interpretation": "공식 타수. 볼넷, HBP, 희생타가 제외됨.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": None,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "H",
        "display_name": "안타",
        "category": "observed",
        "formula": "1B + 2B + 3B + HR",
        "interpretation": "안타 총 횟수.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "1B",
        "display_name": "단타",
        "category": "observed",
        "formula": "H - 2B - 3B - HR",
        "interpretation": "단타 수.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "2B",
        "display_name": "2루타",
        "category": "observed",
        "formula": "직접 집계",
        "interpretation": "2루타 수.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "3B",
        "display_name": "3루타",
        "category": "observed",
        "formula": "직접 집계",
        "interpretation": "3루타 수. 주루 능력과 타구 특성이 반영됨.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "HR",
        "display_name": "홈런",
        "category": "observed",
        "formula": "직접 집계",
        "interpretation": "홈런 수. 타자가 가장 직접 통제하기 쉬운 이벤트 중 하나.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "BB",
        "display_name": "볼넷",
        "category": "observed",
        "formula": "직접 집계 (IBB 포함)",
        "interpretation": "볼넷 수. 선구안을 반영하는 중요 지표.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "IBB",
        "display_name": "고의사구",
        "category": "observed",
        "formula": "직접 집계",
        "interpretation": "고의사구 수. wOBA 계산에서는 제외됨.",
        "implementation_status": "implemented",
        "context_neutral": False,
        "context_dependent": True,
        "higher_is_better": None,
        "version": "v1.0.0",
        "notes": "wOBA에서 IBB는 타자 실력으로 보지 않아 제외됨",
    },
    {
        "name": "HBP",
        "display_name": "사구",
        "category": "observed",
        "formula": "직접 집계",
        "interpretation": "투수에게 맞은 공. 출루 기회로 득점가치 있음.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "SO",
        "display_name": "삼진 (타자)",
        "category": "observed",
        "formula": "직접 집계",
        "interpretation": "삼진 당한 횟수. 삼진은 BABIP 운을 배제하므로 일관성 있는 신호.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": False,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "SF",
        "display_name": "희생플라이",
        "category": "observed",
        "formula": "직접 집계",
        "interpretation": "희생플라이. OBP/wOBA 분모에 포함.",
        "implementation_status": "implemented",
        "context_neutral": False,
        "context_dependent": True,
        "higher_is_better": None,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "SH",
        "display_name": "희생번트",
        "category": "observed",
        "formula": "직접 집계",
        "interpretation": "번트로 아웃되며 주자를 진루시킨 타석.",
        "implementation_status": "implemented",
        "context_neutral": False,
        "context_dependent": True,
        "higher_is_better": None,
        "version": "v1.0.0",
        "notes": "번트의 기대득점 효과는 상황에 따라 다름 (The Book 참고)",
    },
    {
        "name": "GDP",
        "display_name": "병살타",
        "category": "observed",
        "formula": "직접 집계",
        "interpretation": "병살타 횟수. 음의 득점가치를 가짐.",
        "implementation_status": "implemented",
        "context_neutral": False,
        "context_dependent": True,
        "higher_is_better": False,
        "version": "v1.0.0",
        "notes": None,
    },
    # ──────────────────────────────────────────
    # 타격 비율 지표 (rate)
    # ──────────────────────────────────────────
    {
        "name": "AVG",
        "display_name": "타율",
        "category": "rate",
        "formula": "H / AB",
        "interpretation": "가장 단순한 타격 지표. 볼넷·장타 가치를 무시하는 한계가 있다. 300타수 이상에서 안정화 시작.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "Efron & Morris (1975): 표본이 적을수록 리그 평균으로 shrinkage해야 함",
    },
    {
        "name": "OBP",
        "display_name": "출루율",
        "category": "rate",
        "formula": "(H + BB + HBP) / (AB + BB + HBP + SF)",
        "interpretation": "볼넷·사구 포함 출루 능력. AVG보다 득점 예측력 우수.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "SLG",
        "display_name": "장타율",
        "category": "rate",
        "formula": "(1B + 2×2B + 3×3B + 4×HR) / AB",
        "interpretation": "장타력을 반영. TB/AB 형태이므로 득점가치를 어느 정도 반영함.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "OPS",
        "display_name": "OPS",
        "category": "rate",
        "formula": "OBP + SLG",
        "interpretation": "OBP와 SLG를 단순 합산. 편리하지만 OBP가 과소평가됨. wOBA가 더 정확한 대안.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "OBP의 실제 가중치는 SLG의 약 1.8배이므로 단순 합산은 부정확",
    },
    {
        "name": "ISO",
        "display_name": "장타력 지수",
        "category": "rate",
        "formula": "SLG - AVG",
        "interpretation": "순수 장타력. 단타를 제외한 extra-base hit 능력을 반영.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "BB%",
        "display_name": "볼넷 비율",
        "category": "rate",
        "formula": "BB / PA",
        "interpretation": "선구안 측정. 약 100 PA부터 안정화 시작.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "안정화 포인트: ~120 PA",
    },
    {
        "name": "K%",
        "display_name": "삼진 비율 (타자)",
        "category": "rate",
        "formula": "SO / PA",
        "interpretation": "삼진 당하는 비율. 약 60~80 PA부터 빠르게 안정화.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": False,
        "version": "v1.0.0",
        "notes": "안정화 포인트: ~80 PA",
    },
    {
        "name": "BABIP",
        "display_name": "인플레이 타율",
        "category": "rate",
        "formula": "(H - HR) / (AB - SO - HR + SF)",
        "interpretation": "인플레이 타구의 안타 비율. 운·타구질·수비가 혼합됨. 리그 평균은 보통 .290~.310.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": None,
        "version": "v1.0.0",
        "notes": "안정화 포인트: ~820 PA. BABIP 이상 편차는 회귀 가능성 신호.",
    },
    {
        "name": "wOBA",
        "display_name": "가중 출루율",
        "category": "run_value",
        "formula": "(w_BB×uBB + w_HBP×HBP + w_1B×1B + w_2B×2B + w_3B×3B + w_HR×HR) / (AB + uBB + SF + HBP)",
        "interpretation": "각 타격 이벤트에 득점가치를 가중한 출루율. OPS보다 정확하게 공격 생산력을 반영.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "KBO 전용 wOBA weight는 KBO RE table 기반 추정 필요 (현재 MLB placeholder 사용)",
    },
    {
        "name": "wRAA",
        "display_name": "리그 평균 대비 가중 득점 기여",
        "category": "run_value",
        "formula": "((wOBA - lgwOBA) / wOBA_scale) × PA",
        "interpretation": "리그 평균 타자 대비 추가 득점 기여. 양수=평균 초과, 음수=평균 미달.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "wRC",
        "display_name": "가중 득점 생산",
        "category": "run_value",
        "formula": "wRAA + (lgR/PA × PA)",
        "interpretation": "wRAA에 리그 평균 득점을 더해 절대적 득점 생산량으로 변환.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "wRC+",
        "display_name": "파크/리그 보정 가중 득점 생산",
        "category": "run_value",
        "formula": "(wRC/PA) / (PF × lgwRC/PA) × 100",
        "interpretation": "100=리그 평균. 150이면 50% 우수. 구장·리그 보정됨. 단일 공격 지표로 가장 우수.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "구장 보정 factor는 현재 1.0 (placeholder). KBO 파크팩터 추정 필요.",
    },
    # ──────────────────────────────────────────
    # 투수 기본 지표
    # ──────────────────────────────────────────
    {
        "name": "IP",
        "display_name": "이닝",
        "category": "observed",
        "formula": "직접 집계 (소수점: .1=1/3, .2=2/3)",
        "interpretation": "투구한 이닝 수. 내구성·volume 측정.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "ER",
        "display_name": "자책점",
        "category": "observed",
        "formula": "직접 집계",
        "interpretation": "오류 없이 허용한 실점. ERA의 기반.",
        "implementation_status": "implemented",
        "context_neutral": False,
        "context_dependent": True,
        "higher_is_better": False,
        "version": "v1.0.0",
        "notes": "earned/unearned 구분은 기록원 판단에 따라 가변적",
    },
    {
        "name": "ERA",
        "display_name": "평균 자책점",
        "category": "rate",
        "formula": "9 × ER / IP",
        "interpretation": "9이닝당 허용 자책점. 결과 지표이며 수비·운에 영향받음. FIP와 비교해 ERA-FIP 갭을 봐야 함.",
        "implementation_status": "implemented",
        "context_neutral": False,
        "context_dependent": True,
        "higher_is_better": False,
        "version": "v1.0.0",
        "notes": "ERA < FIP이면 수비/운 혜택, ERA > FIP이면 운 불운 가능성",
    },
    {
        "name": "RA9",
        "display_name": "9이닝당 실점",
        "category": "rate",
        "formula": "9 × R / IP",
        "interpretation": "비자책 포함 실점. ERA보다 실제 실점 방어를 직접 반영.",
        "implementation_status": "implemented",
        "context_neutral": False,
        "context_dependent": True,
        "higher_is_better": False,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "WHIP",
        "display_name": "이닝당 출루 허용",
        "category": "rate",
        "formula": "(BB + H) / IP",
        "interpretation": "이닝당 볼넷+안타 허용수. 빠르게 계산 가능한 투수 지표.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": False,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "K/9",
        "display_name": "9이닝당 삼진",
        "category": "rate",
        "formula": "9 × K / IP",
        "interpretation": "삼진 능력의 per-9 측정치. K%로 보는 것이 BF 기준으로 더 정확함.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "BB/9",
        "display_name": "9이닝당 볼넷",
        "category": "rate",
        "formula": "9 × BB / IP",
        "interpretation": "제구력 측정. 낮을수록 좋음.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": False,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "HR/9",
        "display_name": "9이닝당 홈런",
        "category": "rate",
        "formula": "9 × HR / IP",
        "interpretation": "홈런 허용 비율. FIP의 핵심 입력값 중 하나.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": False,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "K%_pit",
        "display_name": "삼진 비율 (투수)",
        "category": "rate",
        "formula": "K / BF",
        "interpretation": "대면 타자 대비 삼진 비율. K/9보다 타자 수 기준으로 더 정확.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "BB%_pit",
        "display_name": "볼넷 비율 (투수)",
        "category": "rate",
        "formula": "BB / BF",
        "interpretation": "대면 타자 대비 볼넷 비율. 제구력 지표.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": False,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "K-BB%",
        "display_name": "삼진-볼넷 비율",
        "category": "rate",
        "formula": "K% - BB%",
        "interpretation": "삼진 능력과 볼넷 절제의 합산 지표. 높을수록 우수.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "FIP",
        "display_name": "수비무관 평균자책점",
        "category": "run_value",
        "formula": "(13×HR + 3×(BB+HBP) - 2×K) / IP + FIP_constant",
        "interpretation": "투수가 직접 통제하는 HR/BB/HBP/K만으로 계산. ERA보다 미래 성적 예측력이 높음.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": False,
        "version": "v1.0.0",
        "notes": "FIP_constant는 lgERA = lgFIP가 되도록 보정. KBO 전용 constant 추정 필요.",
    },
    {
        "name": "FIP-",
        "display_name": "파크/리그 보정 FIP",
        "category": "run_value",
        "formula": "(FIP / (PF × lgFIP)) × 100",
        "interpretation": "100=리그 평균. 100 미만이 우수. wRC+의 투수판.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": False,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "xFIP",
        "display_name": "기대 수비무관 평균자책점",
        "category": "run_value",
        "formula": "FIP에서 HR을 리그 평균 FB×HR/FB 비율로 대체",
        "interpretation": "HR 운을 배제한 FIP. 투수의 HR 허용은 FB% × lgHR/FB%로 정규화.",
        "implementation_status": "placeholder",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": False,
        "version": "v1.0.0",
        "notes": "FB% 데이터 필요. KBO 데이터 확보 후 구현 예정.",
    },
    {
        "name": "SIERA",
        "display_name": "기술 지표 기반 ERA",
        "category": "run_value",
        "formula": "K%, BB%, GB%, FB%, LD% 기반 비선형 회귀",
        "interpretation": "FIP보다 타구 유형을 추가 반영한 투수 ERA 추정치.",
        "implementation_status": "placeholder",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": False,
        "version": "v1.0.0",
        "notes": "타구 유형 데이터 필요. Future 구현 예정.",
    },
    # ──────────────────────────────────────────
    # 주루 지표
    # ──────────────────────────────────────────
    {
        "name": "SB",
        "display_name": "도루",
        "category": "observed",
        "formula": "직접 집계",
        "interpretation": "도루 성공 수.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "CS",
        "display_name": "도루 실패",
        "category": "observed",
        "formula": "직접 집계",
        "interpretation": "도루 실패 수. CS는 아웃이므로 run value가 음수.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": False,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "SB%",
        "display_name": "도루 성공률",
        "category": "rate",
        "formula": "SB / (SB + CS)",
        "interpretation": "도루 시도 대비 성공률. 손익분기점은 약 70~75%.",
        "implementation_status": "placeholder",
        "context_neutral": False,
        "context_dependent": True,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "손익분기점은 RE table 기반으로 계산 필요 (The Book 참고)",
    },
    {
        "name": "wSB",
        "display_name": "도루 득점가치",
        "category": "run_value",
        "formula": "(SB × run_value_sb) + (CS × run_value_cs)",
        "interpretation": "도루와 실패의 net run value. 양수면 이득, 음수면 손해.",
        "implementation_status": "placeholder",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "RE table 기반 run value 필요",
    },
    # ──────────────────────────────────────────
    # 수비 지표
    # ──────────────────────────────────────────
    {
        "name": "E",
        "display_name": "실책",
        "category": "observed",
        "formula": "직접 집계",
        "interpretation": "실책 수. 낮을수록 좋지만 범위·포지션 차이를 무시함.",
        "implementation_status": "implemented",
        "context_neutral": False,
        "context_dependent": True,
        "higher_is_better": False,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "FPct",
        "display_name": "수비율",
        "category": "rate",
        "formula": "(PO + A) / (PO + A + E)",
        "interpretation": "수비율. 손쉬운 플레이에 편향되어 범위를 무시하는 한계.",
        "implementation_status": "placeholder",
        "context_neutral": False,
        "context_dependent": True,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "수비 능력의 대략적인 지표에 불과함",
    },
    {
        "name": "UZR",
        "display_name": "통산 범위 기여",
        "category": "run_value",
        "formula": "복잡한 MGL 공식 (타구 위치·속도 기반)",
        "interpretation": "리그 평균 수비수 대비 득점 기여. 3년 누적이 필요.",
        "implementation_status": "future",
        "context_neutral": False,
        "context_dependent": True,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "Statcast 수준 타구 추적 데이터 필요. KBO에서는 현재 불가.",
    },
    {
        "name": "DRS",
        "display_name": "수비 런 세이브",
        "category": "run_value",
        "formula": "BIS 비디오 스카우팅 기반 플러스/마이너스 시스템",
        "interpretation": "수비로 절약/허용한 득점. 0=평균.",
        "implementation_status": "future",
        "context_neutral": False,
        "context_dependent": True,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "상세 타구 데이터 필요. KBO에서 현재 미제공.",
    },
    # ──────────────────────────────────────────
    # 팀 지표
    # ──────────────────────────────────────────
    {
        "name": "WPct",
        "display_name": "승률",
        "category": "rate",
        "formula": "W / (W + L)",
        "interpretation": "실제 승률. 득실점 기반 기대승률과 비교가 중요.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "RS",
        "display_name": "득점",
        "category": "observed",
        "formula": "직접 집계",
        "interpretation": "팀 득점 합계.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "RA",
        "display_name": "실점",
        "category": "observed",
        "formula": "직접 집계",
        "interpretation": "팀 실점 합계.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": False,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "RD",
        "display_name": "득실점 차",
        "category": "observed",
        "formula": "RS - RA",
        "interpretation": "득점에서 실점을 뺀 수치. 팀 강도의 원초적 지표.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "PythWPct",
        "display_name": "피타고라스 기대승률",
        "category": "projection",
        "formula": "RS^x / (RS^x + RA^x)  (x≈1.83~2.0)",
        "interpretation": "득점과 실점만으로 추정한 기대승률. 실제 승률과 비교해 운/클러치 퍼포먼스를 분리.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "KBO 최적 exponent x는 역사적 KBO 데이터 회귀로 추정 필요 (현재 1.83 사용)",
    },
    {
        "name": "ExpW",
        "display_name": "기대 승수",
        "category": "projection",
        "formula": "PythWPct × G",
        "interpretation": "득실점 기반 기대 승수. 실제 승수와의 차이가 over/under-performance 지표.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    {
        "name": "AMinusE",
        "display_name": "실제 - 기대 승수",
        "category": "projection",
        "formula": "W - ExpW",
        "interpretation": "양수면 기대보다 많이 이김 (불펜·클러치 등이 요인). 음수면 회귀 후보.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": None,
        "version": "v1.0.0",
        "notes": "큰 양수는 다음 시즌 회귀 가능성 신호 (The Book 참고)",
    },
    # ──────────────────────────────────────────
    # 상황/맥락 지표 (win_value)
    # ──────────────────────────────────────────
    {
        "name": "RE24",
        "display_name": "기대득점 변화",
        "category": "run_value",
        "formula": "runs_scored + RE(after state) - RE(before state)",
        "interpretation": "플레이가 이닝 기대득점을 얼마나 바꿨는지. context-independent run value.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "24 base-out state 기반. KBO RE table 플레이스홀더 사용 중.",
    },
    {
        "name": "WPA",
        "display_name": "승리확률 기여",
        "category": "win_value",
        "formula": "WE(after) - WE(before)",
        "interpretation": "플레이 전후 홈팀 승리확률 변화. context-dependent (상황에 따라 같은 홈런도 WPA가 다름).",
        "implementation_status": "implemented",
        "context_neutral": False,
        "context_dependent": True,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "동점 9회말 홈런과 10:0 리드 홈런은 WPA가 크게 다름",
    },
    {
        "name": "WE",
        "display_name": "승리 확률",
        "category": "win_value",
        "formula": "lookup(inning, half, score_diff, outs, base_state)",
        "interpretation": "현재 상황에서 홈팀이 이길 확률. 0=확실 패, 1=확실 승.",
        "implementation_status": "implemented",
        "context_neutral": False,
        "context_dependent": True,
        "higher_is_better": None,
        "version": "v1.0.0",
        "notes": "KBO WE table 플레이스홀더 사용 중",
    },
    {
        "name": "LI",
        "display_name": "레버리지 지수",
        "category": "win_value",
        "formula": "|WPA_actual| / |WPA_average|",
        "interpretation": "이 타석이 평균 대비 얼마나 중요한 승부처인지. 1=평균, 2=2배 중요, 3+=클러치.",
        "implementation_status": "implemented",
        "context_neutral": False,
        "context_dependent": True,
        "higher_is_better": None,
        "version": "v1.0.0",
        "notes": "Tango/Lichtman/Dolphin (The Book) 참고",
    },
    {
        "name": "Clutch",
        "display_name": "클러치 지수",
        "category": "win_value",
        "formula": "WPA / LI - context-neutral WPA",
        "interpretation": "고압 상황에서의 추가 성과. 재현성 낮아 해석 주의 필요.",
        "implementation_status": "placeholder",
        "context_neutral": False,
        "context_dependent": True,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "FanGraphs 정의 참고. 재현성 낮음.",
    },
    # ──────────────────────────────────────────
    # 보정/예측 지표 (projection)
    # ──────────────────────────────────────────
    {
        "name": "adjAVG",
        "display_name": "회귀 보정 타율",
        "category": "projection",
        "formula": "λ × observed_avg + (1-λ) × league_avg  (λ=AB/(AB+k))",
        "interpretation": "표본이 작을수록 리그 평균으로 수렴. 잠재 실력의 empirical Bayes 추정.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "Efron & Morris (1975) / Brown (2008) 기반 shrinkage 접근",
    },
    {
        "name": "adjOPS",
        "display_name": "회귀 보정 OPS",
        "category": "projection",
        "formula": "λ × observed_OPS + (1-λ) × league_OPS",
        "interpretation": "OPS의 shrinkage 추정. 표본이 작을수록 불확실성이 크다.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "안정화 포인트 약 200 PA",
    },
    {
        "name": "reliability",
        "display_name": "표본 안정성 점수",
        "category": "projection",
        "formula": "sample_size / (sample_size + stabilization_point)",
        "interpretation": "0~1 스케일. 1에 가까울수록 관측값 신뢰도 높음.",
        "implementation_status": "implemented",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": None,
    },
    # ──────────────────────────────────────────
    # WAR
    # ──────────────────────────────────────────
    {
        "name": "WAR_lite",
        "display_name": "WAR (경량)",
        "category": "win_value",
        "formula": "(타격득점 + 주루득점 + 수비득점 - 대체수준득점) / 득점당승리",
        "interpretation": "대체수준 선수 대비 승리 기여. 단일 숫자로 선수 총 가치를 표현하는 지표.",
        "implementation_status": "placeholder",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "openWAR처럼 WAR는 불확실성 있는 추정치. 수비 기여는 데이터 한계로 placeholder.",
    },
    # ──────────────────────────────────────────
    # Statcast / 트래킹 placeholder
    # ──────────────────────────────────────────
    {
        "name": "ExitVelo",
        "display_name": "타구 속도",
        "category": "tracking",
        "formula": "타구 속도 (km/h)",
        "interpretation": "타구의 출발 속도. 타격 파워의 직접 측정치.",
        "implementation_status": "future",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "KBO 공개 데이터에 현재 미제공. Statcast 수준 트래킹 필요.",
    },
    {
        "name": "LaunchAngle",
        "display_name": "발사각",
        "category": "tracking",
        "formula": "타구 발사각 (도)",
        "interpretation": "이상적인 발사각 10~30도에서 장타 확률 높음.",
        "implementation_status": "future",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": None,
        "version": "v1.0.0",
        "notes": "KBO 트래킹 데이터 필요.",
    },
    {
        "name": "HardHit%",
        "display_name": "강타구 비율",
        "category": "tracking",
        "formula": "Exit Velo ≥ 145 km/h 타구 비율",
        "interpretation": "강타구 비율. BABIP 운을 일부 배제한 컨택 품질 지표.",
        "implementation_status": "future",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "KBO 트래킹 데이터 필요.",
    },
    {
        "name": "Barrel%",
        "display_name": "베럴 비율",
        "category": "tracking",
        "formula": "최적 Exit Velo + Launch Angle 조합 타구 비율",
        "interpretation": "홈런·장타 가능성이 높은 이상적 타구 비율.",
        "implementation_status": "future",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "KBO 트래킹 데이터 필요.",
    },
    {
        "name": "xBA",
        "display_name": "기대 타율",
        "category": "tracking",
        "formula": "Exit Velo + Launch Angle 기반 안타 확률 가중 평균",
        "interpretation": "BABIP 운을 배제한 타구 품질 기반 기대 타율.",
        "implementation_status": "future",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "KBO 트래킹 데이터 필요.",
    },
    {
        "name": "xwOBA",
        "display_name": "기대 가중 출루율",
        "category": "tracking",
        "formula": "타구 품질 기반 기대 wOBA",
        "interpretation": "BABIP 운 배제. 실제 wOBA와의 차이가 운/회귀 가능성 신호.",
        "implementation_status": "future",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "KBO 트래킹 데이터 필요.",
    },
    {
        "name": "SprintSpeed",
        "display_name": "주루 스피드",
        "category": "tracking",
        "formula": "feet per second (MLB 기준)",
        "interpretation": "주루 능력의 직접 측정치.",
        "implementation_status": "future",
        "context_neutral": True,
        "context_dependent": False,
        "higher_is_better": True,
        "version": "v1.0.0",
        "notes": "KBO 트래킹 데이터 필요.",
    },
]
